name: Actions Workflow

on: [push]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: List Files
        run: |
          pwd
          ls -a
      - name: Checkout
        #Questa azione fa un fetch del repository corrente e fa il checkout del commit che ha scatenato la action corrente
        uses: actions/checkout@v1 
        run: |
          pwd
          ls -a
      - name: Simple JS Actions
        id: greets
        #Un'azione può essere importata da un repo pubblico
        uses: actions/hello-world-javascript-action@v1 
        with: #Qui specifico gli input dell'action
          who-to-greet: John #Questo è un parametro specifico dell'azione
      - name: Log Greeting time
        #Stampo l'output dell'azione con la notazione ${{}}. Steps è una variabile di github actions
        #time è il nome della variabile che contiene l'output in questa specifica azione (vedi documentation)
        run: echo "${{ steps.greets.outputs.time }}"